### ISSUE TITLE
بروز کردن bootstrap

### ISSUE THREAD

**Issue by amir2002002** [theme-makers/fox-theme#7]
خانم احسانی bootstrap نسخه جدید داده خواهشا فایل های توی پوشه libraries رو پاک کنید و bootstrap جدید بریزین.

**Comment by faehsani** [comment]
> خانم احسانی bootstrap نسخه جدید داده خواهشا فایل های توی پوشه libraries رو پاک کنید و bootstrap جدید بریزین.

**Comment by faehsani** [comment]
> خانم احسانی bootstrap نسخه جدید داده خواهشا فایل های توی پوشه libraries رو پاک کنید و bootstrap جدید بریزین.

انجام شد
