### ISSUE TITLE
slider & category box

### ISSUE THREAD

**Issue by amir2002002** [theme-makers/fox-theme#8]
![temp](https://user-images.githubusercontent.com/55617863/115187350-67476d80-a0f8-11eb-8fa8-b2f1ed3eccd7.png)

این قسمت ها به صورت تمام عرض انجام شوند

**Comment by faehsani** [comment]
بخش اسلایدر انجام شد

**Comment by amir2002002** [comment]
> بخش اسلایدر انجام شد

برای تعریف فونت به شکل زیر انواع فرمت ها را صدا بزنید
@font-face {
  font-style: normal;
  font-weight: normal;
  font-family: 'abril_fatfaceregular';
  src: url('abrilfatface-regular-webfont.eot');
  src: url('abrilfatface-regular-webfont.eot?#iefix') format('embedded-opentype'),
       url('abrilfatface-regular-webfont.woff') format('woff'),
       url('abrilfatface-regular-webfont.ttf') format('truetype'),
       url('abrilfatface-regular-webfont.svg#abril_fatfaceregular') format('svg');
}

نکته دوم اینه که قرار بود از اسلایدر خود بوتسترپ استفاده بشه و بعد ها در مراحل بعد کتابخونه هایی مثل اسلیک یا اوول کروسل استفاده بشه
درضمن محل قرار گرفتن لایبرری اوول کروسل کاملا اشتباه. نباید داخل بوتسترپ باشه  

اگر دقت کنید محتوای اسلایدر هم داخل کانتینره که برای شما اینطور نیست

**Comment by faehsani** [comment]
ممنون از ذکر نکات 
چشم تمامی مواردی که گفتید با دقت انجام میشه
